#!/bin/sh

if [ "$1" = "start" ]
then
        . /etc/profile
        printf "mounting filesystem : "

        if [ -e /boot/usb.disk0 ]
        then
                if [ ! -e /etc/kvm.disk0 ]
                then
                        touch /etc/kvm.disk0
                        # use all sdcard free space for data
                        parted -s /dev/mmcblk0 "mkpart primary 25% 100%"
                        sleep 1
                        # resize data filesystem
                        (mkfs.exfat /dev/mmcblk0p3) &
                        sleep 1
                fi
        fi

        if [ -e /dev/mmcblk0p3 ]
        then
                mkdir -p /data
                mount -o uid=debian /dev/mmcblk0p3 /data
        fi

        echo "OK"
fi
