#!/bin/sh

if [ "$1" = "start" ]
then
	base_uid=/sys/class/cvi-base/base_uid
	str_value=$(cat $base_uid | awk '{print $2}')
	if [ -e /proc/ax_proc/uid ]
	then
		base_uid=/proc/ax_proc/uid
		str_value=$(cat $base_uid | awk '{print $2}' | cut -c 3-)_
	fi
	first_uint=$(echo $str_value | cut -d'_' -f1)
	second_uint=$(echo $str_value | cut -d'_' -f2)
	result="$first_uint$second_uint"
	echo $result > /device_key
	# for compatibility with previous network mac addr
	cat $base_uid > /device_key_legacy
fi

