#!/bin/sh
panel=
cp -p /usr/lib/cvitek-fsbl/licheervnano/fip.bin /boot/
cp -p /usr/lib/cvitek-fsbl/licheervnano/u-boot-initial-env /etc/
[ -e /boot/logo.jpeg -o ! -e /usr/lib/cvitek-fsbl/licheervnano/logo.jpeg ] || cp -p  /usr/lib/cvitek-fsbl/licheervnano/logo.jpeg /boot/
sed -i -e 's|#U_BOOT_SYNC_DTBS=".*"|U_BOOT_SYNC_DTBS="true"|' /etc/default/u-boot
if grep -q '/dev/mmcblk0p1.*/boot' /etc/fstab ; then
  sed -i -i 's|#U_BOOT_PARAMETERS=".*"|U_BOOT_PARAMETERS="console=ttyS0,115200 earlycon=sbi root=/dev/mmcblk0p2 rootwait rw"|' /etc/default/u-boot
  grep -q '^U_BOOT_FDT_DIR' /etc/default/u-boot || echo 'U_BOOT_FDT_DIR="/fdt/linux-image-"' >> /etc/default/u-boot
else
  sed -i -i 's|#U_BOOT_PARAMETERS=".*"|U_BOOT_PARAMETERS="console=ttyS0,115200 earlycon=sbi root=/dev/mmcblk0p1 rootwait rw"|' /etc/default/u-boot
  grep -q '^U_BOOT_FDT_DIR' /etc/default/u-boot || echo 'U_BOOT_FDT_DIR="/boot/fdt/linux-image-"' >> /etc/default/u-boot
fi
[ -e /etc/fw_env.config ] || echo '/boot/uboot.env	0x0000          0x20000' > /etc/fw_env.config
[ -e /boot/uboot.env ] || mkenvimage -s 0x20000 -o /boot/uboot.env /etc/u-boot-initial-env
[ -e /boot/board ] || echo "id=maixcam" > /boot/board
grep -q '^name=' /boot/board || echo "name=MaixCAM" >> /boot/board
if [ "X${panel}" != "X" ]; then
  if grep -q '^panel=' /boot/board ; then
    sed -i s/'^panel=.*'/'panel='${panel}/g /boot/board
  else
    echo "panel=${panel}" >> /boot/board
  fi
  grep -q showlogo /boot/uboot.env || mkenvimage -s 0x20000 -o /boot/uboot.env /etc/u-boot-initial-env
elif [ -e /kvmapp ]; then
  grep -q showlogo /boot/uboot.env || mkenvimage -s 0x20000 -o /boot/uboot.env /etc/u-boot-initial-env
else
  ! grep -q showlogo /boot/uboot.env || mkenvimage -s 0x20000 -o /boot/uboot.env /etc/u-boot-initial-env
fi
