#!/bin/sh
if [ ! -e /etc/sysctl.d/10-console-messages.conf ]; then
  cat <<EOM > /etc/sysctl.d/10-console-messages.conf

# the following stops low-level messages on console
kernel.printk = 4 4 1 7
EOM
fi
